name: Deploy to AWS EKS

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t jayeshdesh/e-commerceplatform-backend:latest ./backend
          docker push jayeshdesh/e-commerceplatform-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t jayeshdesh/e-commerceplatform-frontend:latest ./frontend
          docker push jayeshdesh/e-commerceplatform-frontend:latest

  deploy-to-eks:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Restart Backend Deployment
        run: kubectl rollout restart deployment/backend -n default

      - name: Restart Frontend Deployment
        run: kubectl rollout restart deployment/frontend -n default